### PR TITLE
Fixed missing messages section at bottom right place

### PR DESCRIPTION
**Pull request by Ayush-kr-giga**
Screenshot 2024-10-19 at 1 29 53 PM

### CODE REVIEW

**Comment by abhrajit2004** [comment]
@Ayush-kr-giga ok nice but can you make it workable?

**Comment by Ayush-kr-giga** [comment]
Thanks, I can definitely make it working. Should i raise another issue?

**Comment by abhrajit2004** [comment]
@Ayush-kr-giga no need bro
just do the work and make pr

**Comment by Ayush-kr-giga** [comment]
thankyou sir, i am already doing that.
i had a question regarding hacktoberfest that will this count as second contribution or both will be same?

**Comment by abhrajit2004** [comment]
@Ayush-kr-giga as I have accepted your previous contribution, your next PR will be counted as second contribution

**Pull request merged**
