### PR TITLE
working message section

### PR DESCRIPTION
**Pull request by Ayush-kr-giga**
https://github.com/user-attachments/assets/8fd0d467-c20a-4870-9b0b-bff64e828689

### CODE REVIEW

**Comment by Ayush-kr-giga** [comment]
I hope this is what you wanted. Is there anything else i can do for you?

**Comment by abhrajit2004** [comment]
@Ayush-kr-giga It's very nice and this is what I wanted nothing else. Great Work!

**Comment by Ayush-kr-giga** [comment]
Thankyou sir !!

**Comment by abhrajit2004** [comment]
@Ayush-kr-giga bro you can call me by my name lol 😀

**Pull request merged**
